import assert from "node:assert/strict";
import { Script } from "node:vm";
import browserPage from "../src/page.js";

const page=browserPage("a".repeat(32));
const home=browserPage("",true);
assert(page.includes('const roomFromPage="a'.slice(0,24)), "Room marker should be substituted");
assert(!page.includes("ROOM_PLACEHOLDER"), "No raw room placeholder");
assert(home.includes("Không cần mã ghép nối"), "One-tap homepage missing");
assert(page.includes("Nhận từ iPhone") && page.includes("Gửi từ PC"),"Two-way file UI missing");
assert(page.includes("chưa được kiểm toán bảo mật"), "Unverified security warning missing");
assert(page.includes("AES-256-GCM"), "AES-GCM UI missing");
assert(page.includes("crypto.subtle.encrypt"), "Browser encryption missing");
assert(page.includes("crypto.subtle.decrypt"), "Browser decryption missing");
assert(page.includes("crypto.subtle.deriveBits"), "ECDH+HKDF key derivation missing");
assert(!page.includes('input id="code"'),"Code input must be removed");
assert(page.includes('id="pair"'),"One-tap connect button missing");
assert(page.includes("/api/auto-connect"),"Auto connect endpoint missing");
assert(page.includes("Chấp nhận"),"Phone approval message missing");
assert(page.includes('id="received"'),"Received file list missing");
assert(page.includes('className="thumb"'),"Preview thumbnails missing");
assert(page.includes('onloadedmetadata'),"Video duration missing");
const script=page.match(/<script>([\s\S]*?)<\/script>/);
assert(script, "Expected browser script");
new Script(script[1],{filename:"browser.js"});
assert(!page.includes("tối đa 50 MB"),"Old 50 MB cap must be removed");
assert(page.includes("Chọn thư mục để nhận file lớn"),"Large downloads require a streaming save folder");
assert(page.includes("showDirectoryPicker"),"Streaming file-save directory picker missing");
assert(page.includes("createWritable"),"Browser must write received data to disk");
assert(page.includes("file-progress"),"Bounded chunk-ACK protocol missing");
assert(page.includes("PROGRESS_WINDOW=16"),"Window backpressure missing");
assert(page.includes("IN_MEMORY_FALLBACK"),"RAM guard missing");
console.log("PASS B Send v0.5.4 web: no 50MB cap, streamed PC saves, chunk ACK, AES-GCM, syntax");
