import assert from "node:assert/strict";
import { Script } from "node:vm";
import browserPage from "../src/page.js";

const page=browserPage("a".repeat(32));
const home=browserPage("",true);
assert(page.includes('const roomFromPage="a'.slice(0,24)), "Room marker should be substituted");
assert(!page.includes("ROOM_PLACEHOLDER"), "No raw room placeholder");
assert(home.includes("Mã ghép nối"), "Quick Connect homepage missing");
assert(page.includes("Nhận từ iPhone") && page.includes("Gửi từ PC"),"Two-way file UI missing");
assert(page.includes("chưa kiểm toán bảo mật"), "Unverified security warning missing");
assert(page.includes("AES-256-GCM"), "AES-GCM UI missing");
assert(page.includes("crypto.subtle.encrypt"), "Browser encryption missing");
assert(page.includes("crypto.subtle.decrypt"), "Browser decryption missing");
assert(page.includes("crypto.subtle.deriveBits"), "ECDH+HKDF key derivation missing");
assert(page.includes('input id="code"'),"Quick Connect code input missing");
assert(page.includes('id="received"'),"Received file list missing");
assert(page.includes('className="thumb"'),"Preview thumbnails missing");
assert(page.includes('onloadedmetadata'),"Video duration missing");
const script=page.match(/<script>([\s\S]*?)<\/script>/);
assert(script, "Expected browser script");
new Script(script[1],{filename:"browser.js"});
console.log("PASS B Send v0.5 homepage, short-code, ECDH, AES-GCM, previews and JS syntax");
